/**
 * LlmAutoReplyPlugin — a `messageCreate` subscriber that occasionally
 * (by configured probability) injects a context-aware reply generated by
 * a self-hosted LLM.
 *
 * Flow per message: cheap guards -> per-channel reply cooldown + in-flight
 * guard (automatic replies only) -> probability gate (rolled BEFORE any
 * network/fetch, unless the message begins with the force-trigger keyword)
 * -> {@link runLlmAutoReply}, which fetches the recent burst, builds a
 * transcript, calls the LLM, and posts one reply. The channel is marked
 * in-flight before the first await (so a concurrent automatic message in
 * the same channel yields), and the cooldown is recorded only when a reply
 * actually goes out (automatic or force-triggered).
 *
 * Factory pattern (mirrors `createEarthquakePlugin`): per-bot settings
 * are parsed once and the `SelfHostedLlmClient` is captured in the
 * closure, so the returned object is pure data. `deps` exposes a
 * `random` seam for deterministic tests and the host's `blockedChannels`
 * list so blocked channels never trigger.
 */
import { logError } from '../../core/logger';
import type { Plugin } from '../../core/plugin';
import { SelfHostedLlmClient } from '../../infra/llm';
import { parseLlmAutoReplyConfig } from './config';
import { ReplyCooldown } from './internal/cooldown';
import { InFlightChannels } from './internal/in-flight';
import { runLlmAutoReply } from './internal/orchestrator';
import { startsWithForceTrigger } from './internal/trigger';

const PLUGIN_ID = 'llm-auto-reply';
const PLUGIN_VERSION = '1.0.0';

/** Optional collaborators wired by the composition root. */
export interface CreateLlmAutoReplyDeps {
  /** Channel ids (e.g. nijika's `blocked_channels`) that never trigger a reply. */
  readonly blockedChannels?: readonly string[];
  /** Random source in [0, 1); injectable for deterministic tests. */
  readonly random?: () => number;
  /** Reply client; injectable so tests can assert the send path without a real HTTP call. */
  readonly client?: Pick<SelfHostedLlmClient, 'reply'>;
}

export const createLlmAutoReplyPlugin = (
  rawConfig: unknown,
  deps: CreateLlmAutoReplyDeps = {},
): Plugin => {
  const config = parseLlmAutoReplyConfig(rawConfig);
  const client =
    deps.client ??
    new SelfHostedLlmClient({
      endpoint: config.endpoint,
      timeoutMs: config.timeoutMs,
    });
  const random = deps.random ?? Math.random;
  const blockedChannels = new Set(deps.blockedChannels ?? []);
  const cooldown = new ReplyCooldown(config.cooldownSeconds * 1000);
  // Channels with a reply attempt currently in flight. An automatic reply
  // yields to one so two near-simultaneous messages in the same channel
  // cannot both pass the readiness check before either records its cooldown
  // (the check + record straddle an `await`). Reference-counted so an
  // overlapping forced attempt does not clear the guard early. Marked before
  // the await, released in `finally`.
  const inFlight = new InFlightChannels();

  return {
    id: PLUGIN_ID,
    version: PLUGIN_VERSION,
    scope: 'bot',
    critical: false,

    events: {
      messageCreate: async (ctx, message): Promise<void> => {
        if (!config.enabled) return;
        if (message.author.bot) return; // self-loop + bot-feedback guard
        if (message.guildId === null) return; // guild-only
        if (blockedChannels.has(message.channelId)) return;
        if (!message.channel.isSendable()) return;

        const channelId = message.channelId;
        // The triggering message's creation time is the cooldown reference.
        const now = message.createdTimestamp;
        const forced = startsWithForceTrigger(message.content);
        // A force-triggered message fires deterministically: it skips the
        // cooldown, the in-flight guard, and (downstream) the windowSeconds
        // burst check. An automatic reply must respect the per-channel
        // cooldown, yield to an in-flight reply for the channel, and pass the
        // probability roll. The messageCount requirement applies to both.
        if (!forced && !cooldown.isReady(channelId, now)) return;
        if (!forced && inFlight.isActive(channelId)) return;
        if (!forced && random() >= config.probability) return;

        // Mark the channel busy BEFORE the first await so a concurrent
        // automatic message observes it and bails; release it in `finally`.
        // A forced reply also marks the channel so a concurrent automatic
        // reply still yields to it.
        inFlight.begin(channelId);
        try {
          const sent = await runLlmAutoReply({ client, logger: ctx.logger, config }, message);
          // Record only on an actual send, so a no-op attempt (too few
          // messages, out of window, empty transcript, LLM failure) does not
          // suppress the next legitimate reply. A forced reply records too,
          // so a following automatic reply observes the gap.
          if (sent) cooldown.record(channelId, now);
        } catch (err: unknown) {
          logError(ctx.logger, message.guildId, err);
        } finally {
          inFlight.end(channelId);
        }
      },
    },
  };
};

export type { LlmAutoReplyPluginConfig } from './config';
