/**
 * Generic handler registry / factory.
 *
 * Phase 1: the runtime `fs.readdirSync + require()` discovery is replaced
 * by codegen — each handler subdirectory has a `registry.generated.ts`
 * mapping `<subdir name> -> HandlerConstructor`. The `Command` /
 * `ButtonHandler` / etc. index files import their registry and call
 * `factory.registerFromRegistry(REGISTRY)`. The old `register(handlerDir)`
 * shim still works (for any legacy in-tree caller) but is deprecated and
 * will be removed in a later phase.
 */
import fs from 'fs';
import path from 'path';

type HandlerConstructor<T> = new () => T;

export type HandlerRegistry<T> = Readonly<Record<string, HandlerConstructor<T>>>;

export class HandlerFactory<T> {
  private handlerMap = new Map<string, HandlerConstructor<T>>();

  /**
   * Register every handler from a statically-imported registry object
   * generated by `scripts/gen-registry.ts`. Duplicate keys throw — a
   * registry with two entries for the same name is a codegen bug and
   * must fail loudly at startup, not silently overwrite.
   */
  public registerFromRegistry(registry: HandlerRegistry<T>): void {
    for (const [name, Ctor] of Object.entries(registry)) {
      if (this.handlerMap.has(name)) {
        throw new Error(`HandlerFactory: duplicate handler name "${name}"`);
      }
      this.handlerMap.set(name, Ctor);
    }
  }

  /**
   * @deprecated Use {@link registerFromRegistry} with the codegen-produced
   * registry object. Retained only for back-compat with legacy callers
   * that have not migrated yet; will be removed once every site uses the
   * static registry.
   */
  public register(handlerDir: string): void {
    const entries = fs.readdirSync(handlerDir, { withFileTypes: true });

    for (const entry of entries) {
      if (!entry.isDirectory()) continue;

      const name = entry.name;
      const modulePath = path.join(handlerDir, name);

      // eslint-disable-next-line @typescript-eslint/no-var-requires, @typescript-eslint/no-require-imports
      const mod = require(modulePath) as { default?: HandlerConstructor<T> };
      if (!mod.default) continue;

      this.handlerMap.set(name, mod.default);
    }
  }

  public create(name: string): T | undefined {
    const Ctor = this.handlerMap.get(name);
    if (!Ctor) return undefined;
    return new Ctor();
  }

  public getConstructor(name: string): HandlerConstructor<T> | undefined {
    return this.handlerMap.get(name);
  }

  public createAll(): Map<string, T> {
    const handlers = new Map<string, T>();
    this.handlerMap.forEach((Ctor, name) => {
      handlers.set(name, new Ctor());
    });
    return handlers;
  }
}
