/**
 * Generic handler registry / factory.
 *
 * Audit C-5: the legacy `register(handlerDir)` runtime-discovery shim
 * is gone. The codegen path (`scripts/gen-registry.ts` + each handler
 * subdirectory's `registry.generated.ts`) has been the sole live entry
 * since Phase 1; the shim survived only as a 0-caller back-compat
 * stub keeping `eslint-disable @typescript-eslint/no-var-requires`
 * alive in production code. Both are deleted now.
 */

type HandlerConstructor<T> = new () => T;

export type HandlerRegistry<T> = Readonly<Record<string, HandlerConstructor<T>>>;

export class HandlerFactory<T> {
  private handlerMap = new Map<string, HandlerConstructor<T>>();

  /**
   * Register every handler from a statically-imported registry object
   * generated by `scripts/gen-registry.ts`. Duplicate keys throw — a
   * registry with two entries for the same name is a codegen bug and
   * must fail loudly at startup, not silently overwrite.
   */
  public registerFromRegistry(registry: HandlerRegistry<T>): void {
    for (const [name, Ctor] of Object.entries(registry)) {
      if (this.handlerMap.has(name)) {
        throw new Error(`HandlerFactory: duplicate handler name "${name}"`);
      }
      this.handlerMap.set(name, Ctor);
    }
  }

  public create(name: string): T | undefined {
    const Ctor = this.handlerMap.get(name);
    if (!Ctor) return undefined;
    return new Ctor();
  }

  public getConstructor(name: string): HandlerConstructor<T> | undefined {
    return this.handlerMap.get(name);
  }

  public createAll(): Map<string, T> {
    const handlers = new Map<string, T>();
    this.handlerMap.forEach((Ctor, name) => {
      handlers.set(name, new Ctor());
    });
    return handlers;
  }
}
